export const HOME_PAGE = '/'
export const SIGN_IN = '/sign-in'
export const SIGN_UP = '/sign-up'
export const PROMOS = '/promos'
export const INVITE_FRIEND = '/invite-friend'
export const CARD = '/card'
export const SETTINGS = '/settings'